apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harpy

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - deployments.yaml
  - services.yaml
  - networkpolicy.yaml
