apiVersion: v1
kind: Service
metadata:
  name: harpy-relay
spec:
  type: ClusterIP
  selector:
    app: harpy-relay
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: harpy-ingest
spec:
  type: ClusterIP
  selector:
    app: harpy-ingest
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: harpy-fusion
spec:
  type: ClusterIP
  selector:
    app: harpy-fusion
  ports:
    - name: http
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: harpy-graph
spec:
  type: ClusterIP
  selector:
    app: harpy-graph
  ports:
    - name: http
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: harpy-aip
spec:
  type: ClusterIP
  selector:
    app: harpy-aip
  ports:
    - name: http
      port: 8084
      targetPort: 8084
