apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harpy.fullname" . }}-secrets
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
