{{- $ns := default .Release.Namespace .Values.namespaceOverride -}}
{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harpy.fullname" $ }}-{{ $name }}
  namespace: {{ $ns }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "harpy.fullname" $ }}-{{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
---
{{- end }}
{{- end }}
